MVCCoreDM1/Areas/Main/Controllers/ApplicationUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCCoreDM1.DataAccess.Repository.IRepository;
using MVCCoreDM1.IzendaBoundary;
using MVCCoreDM1.Models;
using MVCCoreDM1.Models.ViewModels;
using MVCCoreDM1.Utility;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MVCCoreDM1.Areas.Main.Controllers
{
    [Area("Main")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ApplicationUserController : Controller
    {
        #region Variables
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        #endregion

        #region CTOR
        public ApplicationUserController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _unitOfWork = unitOfWork;
        }
        #endregion

        #region Methods
        // GET: Main/ApplicationUser
        public async Task<IActionResult> Index()
        {
            var applicationUserList = await _unitOfWork.ApplicationUser.GetAllAsync(includeProperties: "Tenant");

            return View(applicationUserList);
        }

        // GET: Main/ApplicationUser/Create
        public IActionResult Create()
        {
            ApplicationUserVM applicationUserVM = new ApplicationUserVM()
            {
                TenantList = _unitOfWork.Tenant.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };

            return View(applicationUserVM);
        }

        // POST: Main/ApplicationUser/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationUserVM applicationUserVM)
        {
            if (ModelState.IsValid)
            {
                int? tenantId = null;

                if (applicationUserVM.SelectedTenantId != null)
                {
                    tenantId = applicationUserVM.SelectedTenantId;

                    applicationUserVM.IsAdmin = false;
                }

                var user = new ApplicationUser
                {
                    UserName = applicationUserVM.UserID,
                    Email = applicationUserVM.UserID,
                    Role = applicationUserVM.SelectedRole,
                    TenantId = applicationUserVM.SelectedTenantId
                };

                var result = await _userManager.CreateAsync(user); // Save new user into client DB

                if (result.Succeeded) // if successful, then start creating a user at Izenda DB
                {
                    var assignedRole = !string.IsNullOrEmpty(applicationUserVM.SelectedRole) ? applicationUserVM.SelectedRole : "Employee"; // set default role if required. As an example, Employee is set by default

                    var existingRole = await _roleManager.FindByNameAsync(assignedRole); // check assigned role exist in client DB.

                    if (existingRole == null)
                    {
                        try
                        {
                            await _roleManager.CreateAsync(new IdentityRole(assignedRole));
                            result = await _userManager.AddToRoleAsync(user, assignedRole);
                        }
                        catch (Exception e)
                        {
                            throw new Exception(e.Message);
                        }
                    }
                    else
                    {
                        result = await _userManager.AddToRoleAsync(user, assignedRole);
                    }

                    if (result.Succeeded)
                    {
                        var izendaAdminAuthToken = IzendaTokenAuthorization.GetIzendaAdminToken();
                        //  user.Tenant = _tenantManager.GetTenantById(Input.SelectedTenantId); // set client DB application user's tenant
                        user.Tenant = _unitOfWork.Tenant.GetFirstOrDefault(t => t.Id == applicationUserVM.SelectedTenantId);
                        var tenantName = user.Tenant?.Name ?? null;

                        // Create a new user at Izenda DB
                        var success = await IzendaUtilities.CreateIzendaUser(
                            tenantName,
                            applicationUserVM.UserID,
                            applicationUserVM.LastName,
                            applicationUserVM.FirstName,
                            applicationUserVM.IsAdmin,
                            assignedRole,
                            izendaAdminAuthToken);

                        if (success)
                            return LocalRedirect("/Main/ApplicationUser");
                    }
                    ModelState.AddModelError(string.Empty, "Failed to create a new user. User already exists in DB.");
                }
                else
                    ModelState.AddModelError(string.Empty, "Failed to create a new user. User already exists in DB.");
            }
            return View(new ApplicationUserVM()
            {
                TenantList = _unitOfWork.Tenant.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            });
        }

        // GET: Dynamic retrieval of roles based on selected tenant
        [HttpGet("GetAllRoles")]
        public async Task<IActionResult> GetAllRoles(string selectedTenant)
        {
            var adminToken = IzendaTokenAuthorization.GetIzendaAdminToken();

            var izendaTenant = await IzendaUtilities.GetIzendaTenantByName(selectedTenant, adminToken);
            var roleDetailsByTenant = await IzendaUtilities.GetAllIzendaRoleByTenant(izendaTenant?.Id ?? null, adminToken);

            var roles = roleDetailsByTenant.Select(r => new { r.Id, r.Name }).ToList();
            SelectList _roleList = new SelectList(roles, "Id", "Name");

            return new JsonResult(_roleList);
        }
        #endregion
    }
}

MVCCoreDM1/Areas/Main/Views/ApplicationUser/Create.cshtml
@model MVCCoreDM1.Models.ViewModels.ApplicationUserVM

@{
    ViewData["Title"] = "Create Tenant";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SelectedTenantId"></label>
                <select asp-for="SelectedTenantId" id="tenantList" asp-items="Model.TenantList" class="form-control" onchange="SelectionChange()">
                    <option value="">Select Tenant</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SelectedRole"></label>
                <select asp-for="SelectedRole" id="roleList" asp-items="Model.RoleList" class="form-control">
                    <option value="">Select Role</option>
                </select>
            </div>
            <div id="isAdminDiv">
                <div class="form-group">
                    <div class="checkbox">
                        <label asp-for="IsAdmin">
                            <input asp-for="IsAdmin" />
                            @Html.DisplayNameFor(m => m.IsAdmin)
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="UserID"></label>
                <input asp-for="UserID" class="form-control" />
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <section>
            <div>
                <h4>Further Instruction</h4>
                <hr />
                <p>
                    If you want to add "Email", or update "TimeZone", "Timestamp Offset", "Language", and "Date Format" for a newly created user, please go to Settings &#8594 User Setup and update it.
                </p>
                <p>
                    *If you don't select tenant, it will create a user under system level.
                </p>
            </div>
        </section>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.66.0-2013.10.09/jquery.blockUI.js">
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            SelectionChange();
        });

        function SelectionChange() {
            var selectedTenant = $("#tenantList option:selected").text();

            if (selectedTenant === "Select Tenant") {
                $("#isAdminDiv").show();
            }
            else {
                $("#isAdminDiv").hide();
            }

            $.blockUI({ message: "<h3> Retrieving role and tenant data now...</h3>" });
            var url = '@Url.Action("GetAllRoles","ApplicationUser")'

            $.ajax({
                type: 'GET',
                contentType: "application/x-www-form-urlencoded",
                dataType: 'json',
                data: { selectedTenant: selectedTenant },
                url: url,

                success: function (result) {
                    $.unblockUI();
                    var options = result.map(function (el, i) {
                        return $("<option></option>").val(el.Value).prop("selected", el.Selected).text(el.text).val(el.text);
                    });
                    $("#roleList").html(options, "Value", "Text")
                },
                error: function () {
                    $.unblockUI();
                    alert("Can't retrieve role list");
                }
            });
        }
    </script>
}

MVCCoreDM1/Areas/Main/Views/ApplicationUser/Index.cshtml
@model IEnumerable<MVCCoreDM1.Models.ApplicationUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tenant)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @if (item.Tenant != null)
                {
                    @Html.DisplayFor(modelItem => item.Tenant.Name);
                }
            </td>
        </tr>
}
    </tbody>
</table>