MVCCoreDM1/Areas/Main/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Dynamic;

namespace MVCCoreDM1.Areas.Main.Controllers
{
    [Area("Main")]
    public class DashboardController : Controller
    {
        #region Variables
        private readonly ILogger<DashboardController> _logger;
        #endregion

        #region CTOR
        public DashboardController(ILogger<DashboardController> logger)
        {
            _logger = logger;
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            // not supposed to be routed Index view
            return NotFound();
        }
        
        /// <summary>
        /// Action for rendering Izenda Dashboard Designer page
        /// </summary>
        /// <returns>DashboardDesigner View</returns>
        [Route("/dashboard/new")] // route from izenda BI page (Explore)
        [Route("Main/Dashboard/DashboardDesigner")] // route from nav-bar
        public IActionResult DashboardDesigner()
        {
            return View();
        }

        /// <summary>
        /// Action for rendering Izenda Dashboard List page
        /// </summary>
        /// <returns>Dashboards View</returns>
        public IActionResult Dashboards()
        {
            return View();
        }

        /// <summary>
        /// Action for rendering a dashboard viewer.
        /// </summary>
        /// <param name="id">The dashboard ID</param>
        /// <returns>DashboardViewer View</returns>
        [Route("izenda/dashboard/edit/{id}")]
        public IActionResult DashboardViewer(string id)
        {
            var query = Request.Query;
            dynamic filters = new ExpandoObject();
            foreach (string key in query.Keys)
            {
                ((IDictionary<string, object>)filters).Add(key, query[key]);
            }

            ViewBag.Id = id;
            ViewBag.filters = JsonConvert.SerializeObject(filters);
            return View();
        }
        #endregion
    }
}

MVCCoreDM1/Areas/Main/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Web;

namespace MVCCoreDM1.Areas.Main.Controllers
{
    [Area("Main")]
    public class ReportController : Controller
    {
        #region Variables
        private readonly ILogger<ReportController> _logger;
        #endregion

        #region CTOR
        public ReportController(ILogger<ReportController> logger)
        {
            _logger = logger;
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            // not supposed to be routed Index view
            return NotFound();
        }

        /// <summary>
        /// Render izenda Report Designer view
        /// </summary>
        /// <returns>View</returns>
        public IActionResult ReportDesigner()
        {
            return View();
        }

        /// <summary>
        /// Render Izenda Report List page
        /// </summary>
        /// <returns>Reports View</returns>
        public IActionResult Reports()
        {
            return View();
        }

        /// <summary>
        /// Render Report Viewer
        /// use case example: sub report (new window option) / from starter kit menu (Report Viewer)
        /// </summary>
        /// <param name="id">Report id used for rendering</param>
        /// <returns>ReportViewer View</returns>
        [Route("izenda/report/view/{id}")]
        public IActionResult ReportViewer(string id)
        {
            var query = Request.Query;
            dynamic filters = new ExpandoObject();
            foreach (string key in query.Keys)
            {
                ((IDictionary<string, object>)filters).Add(key, query[key]);
            }

            ViewBag.overridingFilterQueries = JsonConvert.SerializeObject(filters);
            ViewBag.Id = id;
            return View();
        }

        /// <summary>
        /// Action for rendering Izenda Report Part
        /// Use case example: export pdf
        /// </summary>
        /// <param name="id">report part id</param>
        /// <param name="token">token from url</param>
        /// <returns>ReportPart View</returns>
        [Route("izenda/viewer/reportpart/{id}")]
        public IActionResult ReportPart(Guid id, string token)
        {
            ViewBag.Id = id;
            ViewBag.Token = string.IsNullOrWhiteSpace(token) ? HttpUtility.UrlEncode(Request.Cookies["access_token"]) : token;

            return View();
        }

        /// <summary>
        /// Action for rendering page with multiple report parts.
        /// </summary>
        /// <returns>ReportParts View</returns>
        public IActionResult ReportParts()
        {
            return View();
        }
        #endregion
    }
}

MVCCoreDM1/Views/Shared/_IzendaLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Export Page</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="~/js/izenda/izenda-ui.css" rel="stylesheet" />
    <link href="~/css/izenda_visualizations.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    <script src="~/js/jquery-1.10.2.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/alertify.js"></script>
    <script src="~/js/izenda/izenda_common.js"></script>
    <script src="~/js/izenda/izenda_locales.js"></script>
    <script src="~/js/izenda/izenda_vendors.js"></script>
    <script src="~/js/izenda/izenda_ui.js"></script>
    <script src="~/js/izenda.integrate.js"></script>
    <script src="~/js/izenda.utils.js"></script>
    <script src="~/js/izenda_visualizations.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            DoIzendaConfig();
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="dropdown"]').dropdown();
            $("#reportPartLoader").hide();
            $("#reportPartLoaderText").hide();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVCCoreDM1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCoreDM1</title>

    @*From Izenda*@
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/izenda_visualizations.css" rel="stylesheet" /> @*Map error why?*@
    <link href="~/js/izenda/izenda-ui.css" rel="stylesheet" />

    @*Default from Visual Studio template. Unfortunately, the current version of Izenda BI does not support Bootstrap 4*@
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@
</head>
<body>
    <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <div class="navbar-header pull-left">
                        <a class="navbar-brand" href="https://www.izenda.com/" target="_blank" rel="noopener noreferrer">
                            <img src="https://3u8npt2xyr3u2fgvai49zopv-wpengine.netdna-ssl.com/wp-content/uploads/2019/05/izenda-logo-white.png"
                                 alt="Site Logo" style="height:18px; width: 100px" />
                        </a>
                    </div>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Izenda">Izenda</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Settings">Settings</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" data-toggle="dropdown">
                                    Reports
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="Main" asp-controller="Report" asp-action="ReportDesigner">New Report</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="Main" asp-controller="Report" asp-action="Reports">Report List</a>
                                    </li>
                                    <li class="nav-item">
                                        @*UPDATE YOUR REPORT ID FROM [IzendaReport] TABLE*@
                                        <a class="nav-link text-light" asp-area="Main" asp-controller="Report" asp-action="ReportViewer" asp-route-id="[YOUR REPORT ID]">Report Viewer</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="Main" asp-controller="Report" asp-action="ReportParts">Report Parts</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                                    Dashboards
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="Main" asp-controller="Dashboard" asp-action="DashboardDesigner">New Dashboard</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="Main" asp-controller="Dashboard" asp-action="Dashboards">Dashboard List</a>
                                    </li>
                                    <li class="nav-item">
                                        @*UPDATE YOUR DASHBOARD ID FROM [IzendaDashboard] TABLE*@
                                        <a class="nav-link text-light" asp-area="Main" asp-controller="Dashboard" asp-action="DashboardViewer" asp-route-id="[YOUR DASHBOARD ID]">Dashboard Viewer</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    @*Default from Visual Studio template. Unfortunately, the current version of Izenda BI does not support Bootstrap 4*@
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@

    @*Izenda sources*@
    <script rel="preload" src="~/js/jquery-1.10.2.min.js"></script>
    <script rel="preload" src="~/js/bootstrap.min.js"></script>
    <script rel="preload" src="~/js/site.js" asp-append-version="true"></script>
    <script rel="preload" src="~/js/alertify.js"></script>
    <script rel="prefetch" src="~/js/izenda/izenda_common.js"></script>
    <script rel="prefetch" src="~/js/izenda/izenda_locales.js"></script>
    <script rel="prefetch" src="~/js/izenda/izenda_vendors.js"></script>
    <script rel="prefetch" src="~/js/izenda/izenda_ui.js"></script>
    <script rel="prefetch" src="~/js/izenda.integrate.js"></script>
    <script rel="prefetch" src="~/js/izenda.utils.js"></script>
    <script rel="prefetch" src="~/js/izenda_visualizations.js"></script> @*Map error why?*@

    <script type="text/javascript">
        $(document).ready(function () {
            DoIzendaConfig();
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="dropdown"]').dropdown();
            $("#reportPartLoader").hide();
            $("#reportPartLoaderText").hide();
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>